### ISSUE TITLE
log

### ISSUE THREAD

**Issue by zking2000** [zking2000/kafka#16]
```
# GKE Spring Boot OpenTelemetry 纯配置解决方案（无需修改代码）

既然你不想修改Spring Boot应用代码，我提供一个完全基于OpenTelemetry Collector配置的解决方案，专门处理Spring Boot标准日志格式。

## 问题核心

Spring Boot默认日志格式类似：
```
2024-01-15 10:30:45.123  INFO 12345 --- [nio-8080-exec-1] c.example.service.UserService  : User login successful for user: john@example.com
```

你当前使用的filelog receiver无法正确解析这种格式，导致格式不匹配错误。

## 解决方案：纯Collector配置

### 第一步：优化的OpenTelemetry Collector配置

创建 `otel-collector-config.yaml`：

```yaml
receivers:
  # 接收Kong和应用的OTLP数据
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  # 收集Kubernetes容器日志 - 专门优化Spring Boot格式
  filelog:
    include_file_path: true
    include_file_name: true
    include:
      - /var/log/pods/*/*/*.log
    
    # 排除collector自身的日志避免循环
    exclude:
      - /var/log/pods/*/otel-collector/*.log
      - /var/log/pods/opentelemetry/otel-collector/*.log
    
    start_at: beginning
    
    operators:
      # 1. 使用新的container parser处理容器格式
      - id: container-parser
        type: container
      
      # 2. 专门处理Spring Boot日志格式的正则解析器
      - id: spring-boot-parser
        type: regex_parser
        parse_from: attributes.log
        # Spring Boot标准格式：2024-01-15 10:30:45.123  INFO 12345 --- [nio-8080-exec-1] c.example.service.UserService  : User login successful
        regex: '^(?P<timestamp>\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}\.\d{3})\s+(?P<level>\w+)\s+(?P<pid>\d+)\s+---\s+\[(?P<thread>[^\]]+)\]\s+(?P<logger>[\w\.]+)\s*:\s*(?P<message>.*)$'
        timestamp:
          parse_from: attributes.timestamp
          layout: '2006-01-02 15:04:05.000'
        severity:
          parse_from: attributes.level
        if: 'attributes.log matches "^\\d{4}-\\d{2}-\\d{2}\\s+\\d{2}:\\d{2}:\\d{2}\\.\\d{3}\\s+\\w+\\s+\\d+\\s+---"'
      
      # 3. 处理多行日志（如异常堆栈）
      - id: multiline-parser
        type: regex_parser
        parse_from: attributes.log
        regex: '^(?P<continuation_line>\s+at\s+.+|\s+Caused\s+by:.+|\s+\.\.\.\s+\d+\s+more|\s*$)'
        if: 'attributes.log matches "^\\s+(at\\s+.+|Caused\\s+by:.+|\\.\\.\\.|\\s*$)"'
      
      # 4. 移动解析后的字段到正确位置
      - id: move-parsed-fields
        type: move
        from: attributes.level
        to: attributes["log.level"]
        if: 'attributes.level != nil'
      
      - id: move-thread
        type: move
        from: attributes.thread
        to: attributes["thread.name"]
        if: 'attributes.thread != nil'
      
      - id: move-logger
        type: move
        from: attributes.logger
        to: attributes["log.logger"]
        if: 'attributes.logger != nil'
      
      - id: move-pid
        type: move
        from: attributes.pid
        to: attributes["process.pid"]
        if: 'attributes.pid != nil'
      
      - id: move-message
        type: move
        from: attributes.message
        to: body
        if: 'attributes.message != nil'
      
      # 5. 添加静态属性标识这是Spring Boot日志
      - id: add-spring-boot-attributes
        type: add
        field: attributes["log.source"]
        value: "spring-boot"
      
      # 6. 清理原始log字段避免重复
      - id: cleanup-original-log
        type: remove
        field: attributes.log
        if: 'attributes.message != nil'

processors:
  # Kubernetes属性处理器 - 添加K8s元数据
  k8sattributes:
    auth_type: "serviceAccount"
    passthrough: false
    filter:
      node_from_env_var: KUBE_NODE_NAME
    extract:
      metadata:
        - k8s.pod.name
        - k8s.pod.uid
        - k8s.deployment.name
        - k8s.namespace.name
        - k8s.node.name
        - k8s.pod.start_time
        - k8s.container.name
      labels:
        - tag_name: service.name
          key: app
          from: pod
        - tag_name: service.version
          key: version
          from: pod
      annotations:
        - tag_name: service.instance.id
          key: pod-template-hash
          from: pod

  # 资源检测处理器
  resourcedetection:
    detectors: [env, gcp, kubernetes]
    timeout: 2s
    override: false

  # 属性处理器 - 统一service.name
  attributes:
    actions:
      # 如果没有service.name，从k8s.deployment.name推导
      - key: service.name
        from_attribute: k8s.deployment.name
        action: insert
      # 设置deployment.environment
      - key: deployment.environment
        value: ${DEPLOYMENT_ENVIRONMENT}
        action: upsert

  # 转换处理器 - 进一步清理和标准化
  transform:
    log_statements:
      # 将Spring Boot的日志级别标准化
      - context: log
        statements:
          - set(severity_text, attributes["log.level"]) where attributes["log.level"] != nil
          - set(severity_number, 9) where attributes["log.level"] == "INFO"
          - set(severity_number, 13) where attributes["log.level"] == "WARN"
          - set(severity_number, 17) where attributes["log.level"] == "ERROR"
          - set(severity_number, 5) where attributes["log.level"] == "DEBUG"
          - set(severity_number, 1) where attributes["log.level"] == "TRACE"

  # 批处理器
  batch:
    timeout: 10s
    send_batch_size: 1024

  # 内存限制器
  memory_limiter:
    check_interval: 1s
    limit_mib: 1000
    spike_limit_mib: 200

exporters:
  # 调试导出器
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

  # OTLP导出器 - 发送到你的后端
  otlp:
    endpoint: ${OTLP_ENDPOINT:-http://jaeger:4317}
    headers:
      authorization: ${OTLP_AUTH_TOKEN}
    tls:
      insecure: true

  # 可选：Loki导出器（如果使用Grafana Loki）
  loki:
    endpoint: ${LOKI_ENDPOINT:-http://loki:3100/loki/api/v1/push}
    tenant_id: ${LOKI_TENANT_ID:-spring-boot}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, k8sattributes, resourcedetection, attributes, batch]
      exporters: [debug, otlp]
      
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, k8sattributes, resourcedetection, attributes, batch]
      exporters: [debug, otlp]
      
    logs:
      receivers: [otlp, filelog]
      processors: [memory_limiter, k8sattributes, resourcedetection, attributes, transform, batch]
      exporters: [debug, otlp]

  extensions: [health_check, pprof]
  
extensions:
  health_check:
    endpoint: 0.0.0.0:13133
    
  pprof:
    endpoint: 0.0.0.0:1777

# 配置Collector自身的遥测数据格式
telemetry:
  logs:
    level: "info"
    development: false
    encoding: "json"
  metrics:
    address: 0.0.0.0:8888
```

### 第二步：Kubernetes部署配置

创建 `otel-collector-daemonset.yaml`：

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: opentelemetry

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: opentelemetry
data:
  otel-collector-config.yaml: |
    # 这里放入上面的完整collector配置

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-collector
  namespace: opentelemetry
  labels:
    app: otel-collector
spec:
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      serviceAccountName: otel-collector
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.110.0
        command: ["/otelcol-contrib"]
        args: 
          - "--config=/conf/otel-collector-config.yaml"
          - "--log-level=info"
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: DEPLOYMENT_ENVIRONMENT
          value: ${DEPLOYMENT_ENVIRONMENT:-production}
        - name: OTLP_ENDPOINT
          value: ${OTLP_ENDPOINT:-http://jaeger:4317}
        - name: OTLP_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: otlp-secret
              key: auth-token
              optional: true
        ports:
        - containerPort: 4317
          protocol: TCP
          name: otlp-grpc
        - containerPort: 4318
          protocol: TCP
          name: otlp-http
        - containerPort: 13133
          protocol: TCP
          name: health
        - containerPort: 8888
          protocol: TCP
          name: metrics
        - containerPort: 1777
          protocol: TCP
          name: pprof
        volumeMounts:
        - name: config
          mountPath: /conf
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        resources:
          limits:
            memory: 2Gi
            cpu: 1000m
          requests:
            memory: 512Mi
            cpu: 200m
        livenessProbe:
          httpGet:
            path: /
            port: 13133
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 13133
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: otel-collector-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      tolerations:
      - operator: Exists
        effect: NoSchedule

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
  namespace: opentelemetry

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces", "nodes", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["replicasets", "deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-collector
subjects:
- kind: ServiceAccount
  name: otel-collector
  namespace: opentelemetry

---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: opentelemetry
  labels:
    app: otel-collector
spec:
  selector:
    app: otel-collector
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
    protocol: TCP
  - name: otlp-http
    port: 4318
    targetPort: 4318
    protocol: TCP
  - name: health
    port: 13133
    targetPort: 13133
    protocol: TCP
  - name: metrics
    port: 8888
    targetPort: 8888
    protocol: TCP
  type: ClusterIP
```

### 第三步：Kong配置

在Kong CP中配置OpenTelemetry插件的endpoint：

```
http://otel-collector.opentelemetry.svc.cluster.local:4318/v1/traces
```

#### 4.1 部署步骤

```bash
# 1. 创建namespace
kubectl create namespace opentelemetry

# 2. 部署Collector
kubectl apply -f otel-collector-daemonset.yaml

# 3. 检查部署状态
kubectl get pods -n opentelemetry -w
```

#### 4.2 验证配置有效性

```bash
# 验证collector启动成功
kubectl logs -f daemonset/otel-collector -n opentelemetry

# 检查健康状态
kubectl port-forward svc/otel-collector 13133:13133 -n opentelemetry &
curl http://localhost:13133/

# 验证Spring Boot日志解析
kubectl logs -f daemonset/otel-collector -n opentelemetry | grep "spring-boot"

# 测试日志收集（在Spring Boot应用中触发一些日志）
curl http://your-spring-app/actuator/health
```

#### 4.3 验证解析效果

成功配置后，你应该看到类似这样的结构化日志输出：

```json
{
  "resourceLogs": [{
    "resource": {
      "attributes": [
        {"key": "service.name", "value": {"stringValue": "your-spring-app"}},
        {"key": "k8s.pod.name", "value": {"stringValue": "your-app-pod-123"}},
        {"key": "k8s.namespace.name", "value": {"stringValue": "default"}},
        {"key": "deployment.environment", "value": {"stringValue": "production"}}
      ]
    },
    "scopeLogs": [{
      "logRecords": [{
        "timeUnixNano": "1641974445123000000",
        "severityText": "INFO",
        "severityNumber": 9,
        "body": {"stringValue": "User login successful for user: john@example.com"},
        "attributes": [
          {"key": "log.source", "value": {"stringValue": "spring-boot"}},
          {"key": "thread.name", "value": {"stringValue": "nio-8080-exec-1"}},
          {"key": "log.logger", "value": {"stringValue": "c.example.service.UserService"}},
          {"key": "process.pid", "value": {"stringValue": "12345"}}
        ]
      }]
    }]
  }]
}
```

## 关键优势

1. **零代码修改**：完全不需要修改Spring Boot应用
2. **智能解析**：专门针对Spring Boot日志格式优化的正则表达式
3. **多行支持**：自动处理异常堆栈等多行日志
4. **元数据丰富**：自动添加Kubernetes和OpenTelemetry元数据
5. **性能优化**：使用内存限制和批处理避免资源问题

### 日志解析失败
```bash
# 检查正则表达式匹配
kubectl exec -it deployment/otel-collector -n opentelemetry -- /bin/sh
# 手动测试正则表达式
```

### 性能问题
- 调整 `memory_limiter` 配置
- 增加 `batch` 处理器的批次大小
- 监控collector的内存和CPU使用

### 格式不匹配
- 检查你的Spring Boot日志格式是否为标准格式
- 如果格式不同，调整正则表达式中的pattern

这个解决方案将完全解决你的格式不匹配问题，同时保持Spring Boot应用代码不变！
```

**Comment by zking2000** [comment]
```
processors:
  filter:
    traces:
      span:
        - 'attributes["http.target"] == "/metrics"'
        - 'attributes["http.url"] != nil and IsMatch(attributes["http.url"], ".*\\/metrics.*")'
        - 'name == "GET /metrics"'

  # 或者使用更精确的过滤
  filter/exclude_metrics:
    traces:
      span:
        - 'attributes["http.route"] == "/metrics"'
        - 'attributes["http.target"] == "/metrics"'
        - 'attributes["url.path"] == "/metrics"'

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [filter/exclude_metrics, resource, batch]  # 把 filter 放在前面
      exporters: [jaeger]
```

**Comment by zking2000** [comment]
```
processors:
  filter:
    traces:
      span:
        - 'attributes["http.target"] == "/metrics"'
        - 'attributes["http.url"] != nil and IsMatch(attributes["http.url"], ".*\\/metrics.*")'
        - 'name == "GET /metrics"'

  # 或者使用更精确的过滤
  filter/exclude_metrics:
    traces:
      span:
        - 'attributes["http.route"] == "/metrics"'
        - 'attributes["http.target"] == "/metrics"'
        - 'attributes["url.path"] == "/metrics"'

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [filter/exclude_metrics, resource, batch]  # 把 filter 放在前面
      exporters: [jaeger]
```
